name: Publish articles on dev.to

on:
  push:
    branches:
      - master

env:
  FILES: "articles/**/*.md"

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish articles on dev.to
        uses: sinedied/publish-devto@v2
        with:
          devto_key: ${{ secrets.DEVTO_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ env.FILES }}
          conventional_commits: true
          branch: master
      - name: Setup nodejs
        uses: actions/setup-node@v3.5.1
      - name: Install Dependencies
        run: cd ./scripts & yarn
      - name: Get article slugs
        run: cd ./scripts && DEVTO_KEY="${{ secrets.DEVTO_TOKEN }}" FILES="${{ env.FILES }}" yarn ts-node ./index.ts
      - name: Create new commit
        run: git config user.name "dev.to getting slug bot"
          git config user.email "cookie.gg.dev@gmail.com"
          git add .
          git commit -m "[bot] get a slug of each posts"
          git push
